FROM node:22-alpine

WORKDIR /app

# Copy only the package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install pnpm
RUN corepack enable

# Install only specific packages you need
RUN pnpm install --prod hono ky @tus/server @tus/file-store      

# TODO IN DEPLOYMENT PERSIST agent_id.txt and /uploads

# Copy your agent code
COPY src/agent ./src/agent

# Set the working directory to the agent
WORKDIR /app/src/agent

 # build step   goes here 
# Run the agent
CMD ["node", "index.js"]